version: '3'


services:
  rubiks:
    image: nginx
    container_name: web
    expose:
      - "80"
      - "443"
    volumes:
      - ./web:/usr/share/nginx/html:ro
    

networks:
  default:
    external:
      name: nginx-proxy
