version: '2'

services:

 netdata:
    image: firehol/netdata
    container_name: netdata
    
   # expose:
   #   - "19999"
    ports:
     - 29999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    

networks:
  default:
    external:
      name: nginx-proxy