version: '3'

services:
 apache:
     image: php:apache
     container_name: apache
     volumes:
         - ./web/:/var/www/html
     expose:
         - "80"
    

networks:
  default:
    external:
      name: nginx-proxy
